// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sports_keypoints_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ComputerVisionServiceClient is the client API for ComputerVisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputerVisionServiceClient interface {
	GetPoseImage(ctx context.Context, in *GetPoseImageRequest, opts ...grpc.CallOption) (*GetPoseImageResponse, error)
	GetPoseData(ctx context.Context, in *GetPoseDataRequest, opts ...grpc.CallOption) (*GetPoseDataResponse, error)
	GetPoseHandImage(ctx context.Context, in *GetPoseHandImageRequest, opts ...grpc.CallOption) (*GetPoseHandImageResponse, error)
	GetPoseHandData(ctx context.Context, in *GetPoseHandDataRequest, opts ...grpc.CallOption) (*GetPoseHandDataResponse, error)
	GetPoseAll(ctx context.Context, in *GetPoseAllRequest, opts ...grpc.CallOption) (*GetPoseAllResponse, error)
	GetPoseImagesFromVideo(ctx context.Context, opts ...grpc.CallOption) (ComputerVisionService_GetPoseImagesFromVideoClient, error)
	GetPoseDataFromVideo(ctx context.Context, opts ...grpc.CallOption) (ComputerVisionService_GetPoseDataFromVideoClient, error)
	GetPoseHandImagesFromVideo(ctx context.Context, opts ...grpc.CallOption) (ComputerVisionService_GetPoseHandImagesFromVideoClient, error)
	GetPoseHandDataFromVideo(ctx context.Context, opts ...grpc.CallOption) (ComputerVisionService_GetPoseHandDataFromVideoClient, error)
	GetPoseAllFromVideo(ctx context.Context, opts ...grpc.CallOption) (ComputerVisionService_GetPoseAllFromVideoClient, error)
}

type computerVisionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewComputerVisionServiceClient(cc grpc.ClientConnInterface) ComputerVisionServiceClient {
	return &computerVisionServiceClient{cc}
}

func (c *computerVisionServiceClient) GetPoseImage(ctx context.Context, in *GetPoseImageRequest, opts ...grpc.CallOption) (*GetPoseImageResponse, error) {
	out := new(GetPoseImageResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.ComputerVisionService/GetPoseImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerVisionServiceClient) GetPoseData(ctx context.Context, in *GetPoseDataRequest, opts ...grpc.CallOption) (*GetPoseDataResponse, error) {
	out := new(GetPoseDataResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.ComputerVisionService/GetPoseData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerVisionServiceClient) GetPoseHandImage(ctx context.Context, in *GetPoseHandImageRequest, opts ...grpc.CallOption) (*GetPoseHandImageResponse, error) {
	out := new(GetPoseHandImageResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.ComputerVisionService/GetPoseHandImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerVisionServiceClient) GetPoseHandData(ctx context.Context, in *GetPoseHandDataRequest, opts ...grpc.CallOption) (*GetPoseHandDataResponse, error) {
	out := new(GetPoseHandDataResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.ComputerVisionService/GetPoseHandData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerVisionServiceClient) GetPoseAll(ctx context.Context, in *GetPoseAllRequest, opts ...grpc.CallOption) (*GetPoseAllResponse, error) {
	out := new(GetPoseAllResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.ComputerVisionService/GetPoseAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *computerVisionServiceClient) GetPoseImagesFromVideo(ctx context.Context, opts ...grpc.CallOption) (ComputerVisionService_GetPoseImagesFromVideoClient, error) {
	stream, err := c.cc.NewStream(ctx, &ComputerVisionService_ServiceDesc.Streams[0], "/sports_keypoints_proto.ComputerVisionService/GetPoseImagesFromVideo", opts...)
	if err != nil {
		return nil, err
	}
	x := &computerVisionServiceGetPoseImagesFromVideoClient{stream}
	return x, nil
}

type ComputerVisionService_GetPoseImagesFromVideoClient interface {
	Send(*GetPoseImageRequest) error
	Recv() (*GetPoseImageResponse, error)
	grpc.ClientStream
}

type computerVisionServiceGetPoseImagesFromVideoClient struct {
	grpc.ClientStream
}

func (x *computerVisionServiceGetPoseImagesFromVideoClient) Send(m *GetPoseImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computerVisionServiceGetPoseImagesFromVideoClient) Recv() (*GetPoseImageResponse, error) {
	m := new(GetPoseImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computerVisionServiceClient) GetPoseDataFromVideo(ctx context.Context, opts ...grpc.CallOption) (ComputerVisionService_GetPoseDataFromVideoClient, error) {
	stream, err := c.cc.NewStream(ctx, &ComputerVisionService_ServiceDesc.Streams[1], "/sports_keypoints_proto.ComputerVisionService/GetPoseDataFromVideo", opts...)
	if err != nil {
		return nil, err
	}
	x := &computerVisionServiceGetPoseDataFromVideoClient{stream}
	return x, nil
}

type ComputerVisionService_GetPoseDataFromVideoClient interface {
	Send(*GetPoseDataRequest) error
	Recv() (*GetPoseDataResponse, error)
	grpc.ClientStream
}

type computerVisionServiceGetPoseDataFromVideoClient struct {
	grpc.ClientStream
}

func (x *computerVisionServiceGetPoseDataFromVideoClient) Send(m *GetPoseDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computerVisionServiceGetPoseDataFromVideoClient) Recv() (*GetPoseDataResponse, error) {
	m := new(GetPoseDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computerVisionServiceClient) GetPoseHandImagesFromVideo(ctx context.Context, opts ...grpc.CallOption) (ComputerVisionService_GetPoseHandImagesFromVideoClient, error) {
	stream, err := c.cc.NewStream(ctx, &ComputerVisionService_ServiceDesc.Streams[2], "/sports_keypoints_proto.ComputerVisionService/GetPoseHandImagesFromVideo", opts...)
	if err != nil {
		return nil, err
	}
	x := &computerVisionServiceGetPoseHandImagesFromVideoClient{stream}
	return x, nil
}

type ComputerVisionService_GetPoseHandImagesFromVideoClient interface {
	Send(*GetPoseHandImageRequest) error
	Recv() (*GetPoseHandImageResponse, error)
	grpc.ClientStream
}

type computerVisionServiceGetPoseHandImagesFromVideoClient struct {
	grpc.ClientStream
}

func (x *computerVisionServiceGetPoseHandImagesFromVideoClient) Send(m *GetPoseHandImageRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computerVisionServiceGetPoseHandImagesFromVideoClient) Recv() (*GetPoseHandImageResponse, error) {
	m := new(GetPoseHandImageResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computerVisionServiceClient) GetPoseHandDataFromVideo(ctx context.Context, opts ...grpc.CallOption) (ComputerVisionService_GetPoseHandDataFromVideoClient, error) {
	stream, err := c.cc.NewStream(ctx, &ComputerVisionService_ServiceDesc.Streams[3], "/sports_keypoints_proto.ComputerVisionService/GetPoseHandDataFromVideo", opts...)
	if err != nil {
		return nil, err
	}
	x := &computerVisionServiceGetPoseHandDataFromVideoClient{stream}
	return x, nil
}

type ComputerVisionService_GetPoseHandDataFromVideoClient interface {
	Send(*GetPoseHandDataRequest) error
	Recv() (*GetPoseHandDataResponse, error)
	grpc.ClientStream
}

type computerVisionServiceGetPoseHandDataFromVideoClient struct {
	grpc.ClientStream
}

func (x *computerVisionServiceGetPoseHandDataFromVideoClient) Send(m *GetPoseHandDataRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computerVisionServiceGetPoseHandDataFromVideoClient) Recv() (*GetPoseHandDataResponse, error) {
	m := new(GetPoseHandDataResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computerVisionServiceClient) GetPoseAllFromVideo(ctx context.Context, opts ...grpc.CallOption) (ComputerVisionService_GetPoseAllFromVideoClient, error) {
	stream, err := c.cc.NewStream(ctx, &ComputerVisionService_ServiceDesc.Streams[4], "/sports_keypoints_proto.ComputerVisionService/GetPoseAllFromVideo", opts...)
	if err != nil {
		return nil, err
	}
	x := &computerVisionServiceGetPoseAllFromVideoClient{stream}
	return x, nil
}

type ComputerVisionService_GetPoseAllFromVideoClient interface {
	Send(*GetPoseAllRequest) error
	Recv() (*GetPoseAllResponse, error)
	grpc.ClientStream
}

type computerVisionServiceGetPoseAllFromVideoClient struct {
	grpc.ClientStream
}

func (x *computerVisionServiceGetPoseAllFromVideoClient) Send(m *GetPoseAllRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computerVisionServiceGetPoseAllFromVideoClient) Recv() (*GetPoseAllResponse, error) {
	m := new(GetPoseAllResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ComputerVisionServiceServer is the server API for ComputerVisionService service.
// All implementations must embed UnimplementedComputerVisionServiceServer
// for forward compatibility
type ComputerVisionServiceServer interface {
	GetPoseImage(context.Context, *GetPoseImageRequest) (*GetPoseImageResponse, error)
	GetPoseData(context.Context, *GetPoseDataRequest) (*GetPoseDataResponse, error)
	GetPoseHandImage(context.Context, *GetPoseHandImageRequest) (*GetPoseHandImageResponse, error)
	GetPoseHandData(context.Context, *GetPoseHandDataRequest) (*GetPoseHandDataResponse, error)
	GetPoseAll(context.Context, *GetPoseAllRequest) (*GetPoseAllResponse, error)
	GetPoseImagesFromVideo(ComputerVisionService_GetPoseImagesFromVideoServer) error
	GetPoseDataFromVideo(ComputerVisionService_GetPoseDataFromVideoServer) error
	GetPoseHandImagesFromVideo(ComputerVisionService_GetPoseHandImagesFromVideoServer) error
	GetPoseHandDataFromVideo(ComputerVisionService_GetPoseHandDataFromVideoServer) error
	GetPoseAllFromVideo(ComputerVisionService_GetPoseAllFromVideoServer) error
	mustEmbedUnimplementedComputerVisionServiceServer()
}

// UnimplementedComputerVisionServiceServer must be embedded to have forward compatible implementations.
type UnimplementedComputerVisionServiceServer struct {
}

func (UnimplementedComputerVisionServiceServer) GetPoseImage(context.Context, *GetPoseImageRequest) (*GetPoseImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoseImage not implemented")
}
func (UnimplementedComputerVisionServiceServer) GetPoseData(context.Context, *GetPoseDataRequest) (*GetPoseDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoseData not implemented")
}
func (UnimplementedComputerVisionServiceServer) GetPoseHandImage(context.Context, *GetPoseHandImageRequest) (*GetPoseHandImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoseHandImage not implemented")
}
func (UnimplementedComputerVisionServiceServer) GetPoseHandData(context.Context, *GetPoseHandDataRequest) (*GetPoseHandDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoseHandData not implemented")
}
func (UnimplementedComputerVisionServiceServer) GetPoseAll(context.Context, *GetPoseAllRequest) (*GetPoseAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoseAll not implemented")
}
func (UnimplementedComputerVisionServiceServer) GetPoseImagesFromVideo(ComputerVisionService_GetPoseImagesFromVideoServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPoseImagesFromVideo not implemented")
}
func (UnimplementedComputerVisionServiceServer) GetPoseDataFromVideo(ComputerVisionService_GetPoseDataFromVideoServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPoseDataFromVideo not implemented")
}
func (UnimplementedComputerVisionServiceServer) GetPoseHandImagesFromVideo(ComputerVisionService_GetPoseHandImagesFromVideoServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPoseHandImagesFromVideo not implemented")
}
func (UnimplementedComputerVisionServiceServer) GetPoseHandDataFromVideo(ComputerVisionService_GetPoseHandDataFromVideoServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPoseHandDataFromVideo not implemented")
}
func (UnimplementedComputerVisionServiceServer) GetPoseAllFromVideo(ComputerVisionService_GetPoseAllFromVideoServer) error {
	return status.Errorf(codes.Unimplemented, "method GetPoseAllFromVideo not implemented")
}
func (UnimplementedComputerVisionServiceServer) mustEmbedUnimplementedComputerVisionServiceServer() {}

// UnsafeComputerVisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputerVisionServiceServer will
// result in compilation errors.
type UnsafeComputerVisionServiceServer interface {
	mustEmbedUnimplementedComputerVisionServiceServer()
}

func RegisterComputerVisionServiceServer(s grpc.ServiceRegistrar, srv ComputerVisionServiceServer) {
	s.RegisterService(&ComputerVisionService_ServiceDesc, srv)
}

func _ComputerVisionService_GetPoseImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoseImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerVisionServiceServer).GetPoseImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.ComputerVisionService/GetPoseImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerVisionServiceServer).GetPoseImage(ctx, req.(*GetPoseImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerVisionService_GetPoseData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoseDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerVisionServiceServer).GetPoseData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.ComputerVisionService/GetPoseData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerVisionServiceServer).GetPoseData(ctx, req.(*GetPoseDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerVisionService_GetPoseHandImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoseHandImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerVisionServiceServer).GetPoseHandImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.ComputerVisionService/GetPoseHandImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerVisionServiceServer).GetPoseHandImage(ctx, req.(*GetPoseHandImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerVisionService_GetPoseHandData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoseHandDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerVisionServiceServer).GetPoseHandData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.ComputerVisionService/GetPoseHandData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerVisionServiceServer).GetPoseHandData(ctx, req.(*GetPoseHandDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerVisionService_GetPoseAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPoseAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputerVisionServiceServer).GetPoseAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.ComputerVisionService/GetPoseAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputerVisionServiceServer).GetPoseAll(ctx, req.(*GetPoseAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ComputerVisionService_GetPoseImagesFromVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputerVisionServiceServer).GetPoseImagesFromVideo(&computerVisionServiceGetPoseImagesFromVideoServer{stream})
}

type ComputerVisionService_GetPoseImagesFromVideoServer interface {
	Send(*GetPoseImageResponse) error
	Recv() (*GetPoseImageRequest, error)
	grpc.ServerStream
}

type computerVisionServiceGetPoseImagesFromVideoServer struct {
	grpc.ServerStream
}

func (x *computerVisionServiceGetPoseImagesFromVideoServer) Send(m *GetPoseImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computerVisionServiceGetPoseImagesFromVideoServer) Recv() (*GetPoseImageRequest, error) {
	m := new(GetPoseImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ComputerVisionService_GetPoseDataFromVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputerVisionServiceServer).GetPoseDataFromVideo(&computerVisionServiceGetPoseDataFromVideoServer{stream})
}

type ComputerVisionService_GetPoseDataFromVideoServer interface {
	Send(*GetPoseDataResponse) error
	Recv() (*GetPoseDataRequest, error)
	grpc.ServerStream
}

type computerVisionServiceGetPoseDataFromVideoServer struct {
	grpc.ServerStream
}

func (x *computerVisionServiceGetPoseDataFromVideoServer) Send(m *GetPoseDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computerVisionServiceGetPoseDataFromVideoServer) Recv() (*GetPoseDataRequest, error) {
	m := new(GetPoseDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ComputerVisionService_GetPoseHandImagesFromVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputerVisionServiceServer).GetPoseHandImagesFromVideo(&computerVisionServiceGetPoseHandImagesFromVideoServer{stream})
}

type ComputerVisionService_GetPoseHandImagesFromVideoServer interface {
	Send(*GetPoseHandImageResponse) error
	Recv() (*GetPoseHandImageRequest, error)
	grpc.ServerStream
}

type computerVisionServiceGetPoseHandImagesFromVideoServer struct {
	grpc.ServerStream
}

func (x *computerVisionServiceGetPoseHandImagesFromVideoServer) Send(m *GetPoseHandImageResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computerVisionServiceGetPoseHandImagesFromVideoServer) Recv() (*GetPoseHandImageRequest, error) {
	m := new(GetPoseHandImageRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ComputerVisionService_GetPoseHandDataFromVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputerVisionServiceServer).GetPoseHandDataFromVideo(&computerVisionServiceGetPoseHandDataFromVideoServer{stream})
}

type ComputerVisionService_GetPoseHandDataFromVideoServer interface {
	Send(*GetPoseHandDataResponse) error
	Recv() (*GetPoseHandDataRequest, error)
	grpc.ServerStream
}

type computerVisionServiceGetPoseHandDataFromVideoServer struct {
	grpc.ServerStream
}

func (x *computerVisionServiceGetPoseHandDataFromVideoServer) Send(m *GetPoseHandDataResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computerVisionServiceGetPoseHandDataFromVideoServer) Recv() (*GetPoseHandDataRequest, error) {
	m := new(GetPoseHandDataRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ComputerVisionService_GetPoseAllFromVideo_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputerVisionServiceServer).GetPoseAllFromVideo(&computerVisionServiceGetPoseAllFromVideoServer{stream})
}

type ComputerVisionService_GetPoseAllFromVideoServer interface {
	Send(*GetPoseAllResponse) error
	Recv() (*GetPoseAllRequest, error)
	grpc.ServerStream
}

type computerVisionServiceGetPoseAllFromVideoServer struct {
	grpc.ServerStream
}

func (x *computerVisionServiceGetPoseAllFromVideoServer) Send(m *GetPoseAllResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computerVisionServiceGetPoseAllFromVideoServer) Recv() (*GetPoseAllRequest, error) {
	m := new(GetPoseAllRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ComputerVisionService_ServiceDesc is the grpc.ServiceDesc for ComputerVisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputerVisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sports_keypoints_proto.ComputerVisionService",
	HandlerType: (*ComputerVisionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPoseImage",
			Handler:    _ComputerVisionService_GetPoseImage_Handler,
		},
		{
			MethodName: "GetPoseData",
			Handler:    _ComputerVisionService_GetPoseData_Handler,
		},
		{
			MethodName: "GetPoseHandImage",
			Handler:    _ComputerVisionService_GetPoseHandImage_Handler,
		},
		{
			MethodName: "GetPoseHandData",
			Handler:    _ComputerVisionService_GetPoseHandData_Handler,
		},
		{
			MethodName: "GetPoseAll",
			Handler:    _ComputerVisionService_GetPoseAll_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPoseImagesFromVideo",
			Handler:       _ComputerVisionService_GetPoseImagesFromVideo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetPoseDataFromVideo",
			Handler:       _ComputerVisionService_GetPoseDataFromVideo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetPoseHandImagesFromVideo",
			Handler:       _ComputerVisionService_GetPoseHandImagesFromVideo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetPoseHandDataFromVideo",
			Handler:       _ComputerVisionService_GetPoseHandDataFromVideo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetPoseAllFromVideo",
			Handler:       _ComputerVisionService_GetPoseAllFromVideo_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "computervision.proto",
}
