// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package sports_keypoints_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GolfKeypointsServiceClient is the client API for GolfKeypointsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GolfKeypointsServiceClient interface {
	UploadInputImage(ctx context.Context, in *UploadInputImageRequest, opts ...grpc.CallOption) (*UploadInputImageResponse, error)
	ListInputImagesForUser(ctx context.Context, in *ListInputImagesForUserRequest, opts ...grpc.CallOption) (*ListInputImagesForUserResponse, error)
	ReadInputImage(ctx context.Context, in *ReadInputImageRequest, opts ...grpc.CallOption) (*ReadInputImageResponse, error)
	DeleteInputImage(ctx context.Context, in *DeleteInputImageRequest, opts ...grpc.CallOption) (*DeleteInputImageResponse, error)
	// optional if want specific keypoints
	CalibrateInputImage(ctx context.Context, in *CalibrateInputImageRequest, opts ...grpc.CallOption) (*CalibrateInputImageResponse, error)
	CalculateGolfKeypoints(ctx context.Context, in *CalculateGolfKeypointsRequest, opts ...grpc.CallOption) (*CalculateGolfKeypointsResponse, error)
	ReadGolfKeypoints(ctx context.Context, in *ReadGolfKeypointsRequest, opts ...grpc.CallOption) (*ReadGolfKeypointsResponse, error)
	// if estimated body keypoints are off or have low confidence, client can manually input where body parts are
	UpdateBodyKeypoints(ctx context.Context, in *UpdateBodyKeypointsRequest, opts ...grpc.CallOption) (*UpdateBodyKeypointsResponse, error)
	DeleteGolfKeypoints(ctx context.Context, in *DeleteGolfKeypointsRequest, opts ...grpc.CallOption) (*DeleteGolfKeypointsResponse, error)
}

type golfKeypointsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGolfKeypointsServiceClient(cc grpc.ClientConnInterface) GolfKeypointsServiceClient {
	return &golfKeypointsServiceClient{cc}
}

func (c *golfKeypointsServiceClient) UploadInputImage(ctx context.Context, in *UploadInputImageRequest, opts ...grpc.CallOption) (*UploadInputImageResponse, error) {
	out := new(UploadInputImageResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.GolfKeypointsService/UploadInputImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golfKeypointsServiceClient) ListInputImagesForUser(ctx context.Context, in *ListInputImagesForUserRequest, opts ...grpc.CallOption) (*ListInputImagesForUserResponse, error) {
	out := new(ListInputImagesForUserResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.GolfKeypointsService/ListInputImagesForUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golfKeypointsServiceClient) ReadInputImage(ctx context.Context, in *ReadInputImageRequest, opts ...grpc.CallOption) (*ReadInputImageResponse, error) {
	out := new(ReadInputImageResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.GolfKeypointsService/ReadInputImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golfKeypointsServiceClient) DeleteInputImage(ctx context.Context, in *DeleteInputImageRequest, opts ...grpc.CallOption) (*DeleteInputImageResponse, error) {
	out := new(DeleteInputImageResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.GolfKeypointsService/DeleteInputImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golfKeypointsServiceClient) CalibrateInputImage(ctx context.Context, in *CalibrateInputImageRequest, opts ...grpc.CallOption) (*CalibrateInputImageResponse, error) {
	out := new(CalibrateInputImageResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.GolfKeypointsService/CalibrateInputImage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golfKeypointsServiceClient) CalculateGolfKeypoints(ctx context.Context, in *CalculateGolfKeypointsRequest, opts ...grpc.CallOption) (*CalculateGolfKeypointsResponse, error) {
	out := new(CalculateGolfKeypointsResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.GolfKeypointsService/CalculateGolfKeypoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golfKeypointsServiceClient) ReadGolfKeypoints(ctx context.Context, in *ReadGolfKeypointsRequest, opts ...grpc.CallOption) (*ReadGolfKeypointsResponse, error) {
	out := new(ReadGolfKeypointsResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.GolfKeypointsService/ReadGolfKeypoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golfKeypointsServiceClient) UpdateBodyKeypoints(ctx context.Context, in *UpdateBodyKeypointsRequest, opts ...grpc.CallOption) (*UpdateBodyKeypointsResponse, error) {
	out := new(UpdateBodyKeypointsResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.GolfKeypointsService/UpdateBodyKeypoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *golfKeypointsServiceClient) DeleteGolfKeypoints(ctx context.Context, in *DeleteGolfKeypointsRequest, opts ...grpc.CallOption) (*DeleteGolfKeypointsResponse, error) {
	out := new(DeleteGolfKeypointsResponse)
	err := c.cc.Invoke(ctx, "/sports_keypoints_proto.GolfKeypointsService/DeleteGolfKeypoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GolfKeypointsServiceServer is the server API for GolfKeypointsService service.
// All implementations must embed UnimplementedGolfKeypointsServiceServer
// for forward compatibility
type GolfKeypointsServiceServer interface {
	UploadInputImage(context.Context, *UploadInputImageRequest) (*UploadInputImageResponse, error)
	ListInputImagesForUser(context.Context, *ListInputImagesForUserRequest) (*ListInputImagesForUserResponse, error)
	ReadInputImage(context.Context, *ReadInputImageRequest) (*ReadInputImageResponse, error)
	DeleteInputImage(context.Context, *DeleteInputImageRequest) (*DeleteInputImageResponse, error)
	// optional if want specific keypoints
	CalibrateInputImage(context.Context, *CalibrateInputImageRequest) (*CalibrateInputImageResponse, error)
	CalculateGolfKeypoints(context.Context, *CalculateGolfKeypointsRequest) (*CalculateGolfKeypointsResponse, error)
	ReadGolfKeypoints(context.Context, *ReadGolfKeypointsRequest) (*ReadGolfKeypointsResponse, error)
	// if estimated body keypoints are off or have low confidence, client can manually input where body parts are
	UpdateBodyKeypoints(context.Context, *UpdateBodyKeypointsRequest) (*UpdateBodyKeypointsResponse, error)
	DeleteGolfKeypoints(context.Context, *DeleteGolfKeypointsRequest) (*DeleteGolfKeypointsResponse, error)
	mustEmbedUnimplementedGolfKeypointsServiceServer()
}

// UnimplementedGolfKeypointsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGolfKeypointsServiceServer struct {
}

func (UnimplementedGolfKeypointsServiceServer) UploadInputImage(context.Context, *UploadInputImageRequest) (*UploadInputImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadInputImage not implemented")
}
func (UnimplementedGolfKeypointsServiceServer) ListInputImagesForUser(context.Context, *ListInputImagesForUserRequest) (*ListInputImagesForUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInputImagesForUser not implemented")
}
func (UnimplementedGolfKeypointsServiceServer) ReadInputImage(context.Context, *ReadInputImageRequest) (*ReadInputImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadInputImage not implemented")
}
func (UnimplementedGolfKeypointsServiceServer) DeleteInputImage(context.Context, *DeleteInputImageRequest) (*DeleteInputImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteInputImage not implemented")
}
func (UnimplementedGolfKeypointsServiceServer) CalibrateInputImage(context.Context, *CalibrateInputImageRequest) (*CalibrateInputImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalibrateInputImage not implemented")
}
func (UnimplementedGolfKeypointsServiceServer) CalculateGolfKeypoints(context.Context, *CalculateGolfKeypointsRequest) (*CalculateGolfKeypointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateGolfKeypoints not implemented")
}
func (UnimplementedGolfKeypointsServiceServer) ReadGolfKeypoints(context.Context, *ReadGolfKeypointsRequest) (*ReadGolfKeypointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadGolfKeypoints not implemented")
}
func (UnimplementedGolfKeypointsServiceServer) UpdateBodyKeypoints(context.Context, *UpdateBodyKeypointsRequest) (*UpdateBodyKeypointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBodyKeypoints not implemented")
}
func (UnimplementedGolfKeypointsServiceServer) DeleteGolfKeypoints(context.Context, *DeleteGolfKeypointsRequest) (*DeleteGolfKeypointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGolfKeypoints not implemented")
}
func (UnimplementedGolfKeypointsServiceServer) mustEmbedUnimplementedGolfKeypointsServiceServer() {}

// UnsafeGolfKeypointsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GolfKeypointsServiceServer will
// result in compilation errors.
type UnsafeGolfKeypointsServiceServer interface {
	mustEmbedUnimplementedGolfKeypointsServiceServer()
}

func RegisterGolfKeypointsServiceServer(s grpc.ServiceRegistrar, srv GolfKeypointsServiceServer) {
	s.RegisterService(&GolfKeypointsService_ServiceDesc, srv)
}

func _GolfKeypointsService_UploadInputImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadInputImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolfKeypointsServiceServer).UploadInputImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.GolfKeypointsService/UploadInputImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolfKeypointsServiceServer).UploadInputImage(ctx, req.(*UploadInputImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolfKeypointsService_ListInputImagesForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInputImagesForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolfKeypointsServiceServer).ListInputImagesForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.GolfKeypointsService/ListInputImagesForUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolfKeypointsServiceServer).ListInputImagesForUser(ctx, req.(*ListInputImagesForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolfKeypointsService_ReadInputImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadInputImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolfKeypointsServiceServer).ReadInputImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.GolfKeypointsService/ReadInputImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolfKeypointsServiceServer).ReadInputImage(ctx, req.(*ReadInputImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolfKeypointsService_DeleteInputImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteInputImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolfKeypointsServiceServer).DeleteInputImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.GolfKeypointsService/DeleteInputImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolfKeypointsServiceServer).DeleteInputImage(ctx, req.(*DeleteInputImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolfKeypointsService_CalibrateInputImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalibrateInputImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolfKeypointsServiceServer).CalibrateInputImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.GolfKeypointsService/CalibrateInputImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolfKeypointsServiceServer).CalibrateInputImage(ctx, req.(*CalibrateInputImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolfKeypointsService_CalculateGolfKeypoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateGolfKeypointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolfKeypointsServiceServer).CalculateGolfKeypoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.GolfKeypointsService/CalculateGolfKeypoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolfKeypointsServiceServer).CalculateGolfKeypoints(ctx, req.(*CalculateGolfKeypointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolfKeypointsService_ReadGolfKeypoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadGolfKeypointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolfKeypointsServiceServer).ReadGolfKeypoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.GolfKeypointsService/ReadGolfKeypoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolfKeypointsServiceServer).ReadGolfKeypoints(ctx, req.(*ReadGolfKeypointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolfKeypointsService_UpdateBodyKeypoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBodyKeypointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolfKeypointsServiceServer).UpdateBodyKeypoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.GolfKeypointsService/UpdateBodyKeypoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolfKeypointsServiceServer).UpdateBodyKeypoints(ctx, req.(*UpdateBodyKeypointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GolfKeypointsService_DeleteGolfKeypoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGolfKeypointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GolfKeypointsServiceServer).DeleteGolfKeypoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sports_keypoints_proto.GolfKeypointsService/DeleteGolfKeypoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GolfKeypointsServiceServer).DeleteGolfKeypoints(ctx, req.(*DeleteGolfKeypointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GolfKeypointsService_ServiceDesc is the grpc.ServiceDesc for GolfKeypointsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GolfKeypointsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sports_keypoints_proto.GolfKeypointsService",
	HandlerType: (*GolfKeypointsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadInputImage",
			Handler:    _GolfKeypointsService_UploadInputImage_Handler,
		},
		{
			MethodName: "ListInputImagesForUser",
			Handler:    _GolfKeypointsService_ListInputImagesForUser_Handler,
		},
		{
			MethodName: "ReadInputImage",
			Handler:    _GolfKeypointsService_ReadInputImage_Handler,
		},
		{
			MethodName: "DeleteInputImage",
			Handler:    _GolfKeypointsService_DeleteInputImage_Handler,
		},
		{
			MethodName: "CalibrateInputImage",
			Handler:    _GolfKeypointsService_CalibrateInputImage_Handler,
		},
		{
			MethodName: "CalculateGolfKeypoints",
			Handler:    _GolfKeypointsService_CalculateGolfKeypoints_Handler,
		},
		{
			MethodName: "ReadGolfKeypoints",
			Handler:    _GolfKeypointsService_ReadGolfKeypoints_Handler,
		},
		{
			MethodName: "UpdateBodyKeypoints",
			Handler:    _GolfKeypointsService_UpdateBodyKeypoints_Handler,
		},
		{
			MethodName: "DeleteGolfKeypoints",
			Handler:    _GolfKeypointsService_DeleteGolfKeypoints_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "golfkeypoints.proto",
}
