# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import computervision_pb2 as computervision__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in computervision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputerVisionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPoseImage = channel.unary_unary(
                '/sports_keypoints_proto.ComputerVisionService/GetPoseImage',
                request_serializer=computervision__pb2.GetPoseImageRequest.SerializeToString,
                response_deserializer=computervision__pb2.GetPoseImageResponse.FromString,
                _registered_method=True)
        self.GetPoseData = channel.unary_unary(
                '/sports_keypoints_proto.ComputerVisionService/GetPoseData',
                request_serializer=computervision__pb2.GetPoseDataRequest.SerializeToString,
                response_deserializer=computervision__pb2.GetPoseDataResponse.FromString,
                _registered_method=True)
        self.GetPoseHandImage = channel.unary_unary(
                '/sports_keypoints_proto.ComputerVisionService/GetPoseHandImage',
                request_serializer=computervision__pb2.GetPoseHandImageRequest.SerializeToString,
                response_deserializer=computervision__pb2.GetPoseHandImageResponse.FromString,
                _registered_method=True)
        self.GetPoseHandData = channel.unary_unary(
                '/sports_keypoints_proto.ComputerVisionService/GetPoseHandData',
                request_serializer=computervision__pb2.GetPoseHandDataRequest.SerializeToString,
                response_deserializer=computervision__pb2.GetPoseHandDataResponse.FromString,
                _registered_method=True)
        self.GetPoseAll = channel.unary_unary(
                '/sports_keypoints_proto.ComputerVisionService/GetPoseAll',
                request_serializer=computervision__pb2.GetPoseAllRequest.SerializeToString,
                response_deserializer=computervision__pb2.GetPoseAllResponse.FromString,
                _registered_method=True)
        self.GetPoseImagesFromVideo = channel.stream_stream(
                '/sports_keypoints_proto.ComputerVisionService/GetPoseImagesFromVideo',
                request_serializer=computervision__pb2.GetPoseImageRequest.SerializeToString,
                response_deserializer=computervision__pb2.GetPoseImageResponse.FromString,
                _registered_method=True)
        self.GetPoseDataFromVideo = channel.stream_stream(
                '/sports_keypoints_proto.ComputerVisionService/GetPoseDataFromVideo',
                request_serializer=computervision__pb2.GetPoseDataRequest.SerializeToString,
                response_deserializer=computervision__pb2.GetPoseDataResponse.FromString,
                _registered_method=True)
        self.GetPoseHandImagesFromVideo = channel.stream_stream(
                '/sports_keypoints_proto.ComputerVisionService/GetPoseHandImagesFromVideo',
                request_serializer=computervision__pb2.GetPoseHandImageRequest.SerializeToString,
                response_deserializer=computervision__pb2.GetPoseHandImageResponse.FromString,
                _registered_method=True)
        self.GetPoseHandDataFromVideo = channel.stream_stream(
                '/sports_keypoints_proto.ComputerVisionService/GetPoseHandDataFromVideo',
                request_serializer=computervision__pb2.GetPoseHandDataRequest.SerializeToString,
                response_deserializer=computervision__pb2.GetPoseHandDataResponse.FromString,
                _registered_method=True)
        self.GetPoseAllFromVideo = channel.stream_stream(
                '/sports_keypoints_proto.ComputerVisionService/GetPoseAllFromVideo',
                request_serializer=computervision__pb2.GetPoseAllRequest.SerializeToString,
                response_deserializer=computervision__pb2.GetPoseAllResponse.FromString,
                _registered_method=True)


class ComputerVisionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPoseImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoseData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoseHandImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoseHandData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoseAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoseImagesFromVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoseDataFromVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoseHandImagesFromVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoseHandDataFromVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPoseAllFromVideo(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputerVisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPoseImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoseImage,
                    request_deserializer=computervision__pb2.GetPoseImageRequest.FromString,
                    response_serializer=computervision__pb2.GetPoseImageResponse.SerializeToString,
            ),
            'GetPoseData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoseData,
                    request_deserializer=computervision__pb2.GetPoseDataRequest.FromString,
                    response_serializer=computervision__pb2.GetPoseDataResponse.SerializeToString,
            ),
            'GetPoseHandImage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoseHandImage,
                    request_deserializer=computervision__pb2.GetPoseHandImageRequest.FromString,
                    response_serializer=computervision__pb2.GetPoseHandImageResponse.SerializeToString,
            ),
            'GetPoseHandData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoseHandData,
                    request_deserializer=computervision__pb2.GetPoseHandDataRequest.FromString,
                    response_serializer=computervision__pb2.GetPoseHandDataResponse.SerializeToString,
            ),
            'GetPoseAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPoseAll,
                    request_deserializer=computervision__pb2.GetPoseAllRequest.FromString,
                    response_serializer=computervision__pb2.GetPoseAllResponse.SerializeToString,
            ),
            'GetPoseImagesFromVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.GetPoseImagesFromVideo,
                    request_deserializer=computervision__pb2.GetPoseImageRequest.FromString,
                    response_serializer=computervision__pb2.GetPoseImageResponse.SerializeToString,
            ),
            'GetPoseDataFromVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.GetPoseDataFromVideo,
                    request_deserializer=computervision__pb2.GetPoseDataRequest.FromString,
                    response_serializer=computervision__pb2.GetPoseDataResponse.SerializeToString,
            ),
            'GetPoseHandImagesFromVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.GetPoseHandImagesFromVideo,
                    request_deserializer=computervision__pb2.GetPoseHandImageRequest.FromString,
                    response_serializer=computervision__pb2.GetPoseHandImageResponse.SerializeToString,
            ),
            'GetPoseHandDataFromVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.GetPoseHandDataFromVideo,
                    request_deserializer=computervision__pb2.GetPoseHandDataRequest.FromString,
                    response_serializer=computervision__pb2.GetPoseHandDataResponse.SerializeToString,
            ),
            'GetPoseAllFromVideo': grpc.stream_stream_rpc_method_handler(
                    servicer.GetPoseAllFromVideo,
                    request_deserializer=computervision__pb2.GetPoseAllRequest.FromString,
                    response_serializer=computervision__pb2.GetPoseAllResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sports_keypoints_proto.ComputerVisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sports_keypoints_proto.ComputerVisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputerVisionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPoseImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.ComputerVisionService/GetPoseImage',
            computervision__pb2.GetPoseImageRequest.SerializeToString,
            computervision__pb2.GetPoseImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoseData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.ComputerVisionService/GetPoseData',
            computervision__pb2.GetPoseDataRequest.SerializeToString,
            computervision__pb2.GetPoseDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoseHandImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.ComputerVisionService/GetPoseHandImage',
            computervision__pb2.GetPoseHandImageRequest.SerializeToString,
            computervision__pb2.GetPoseHandImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoseHandData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.ComputerVisionService/GetPoseHandData',
            computervision__pb2.GetPoseHandDataRequest.SerializeToString,
            computervision__pb2.GetPoseHandDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoseAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.ComputerVisionService/GetPoseAll',
            computervision__pb2.GetPoseAllRequest.SerializeToString,
            computervision__pb2.GetPoseAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoseImagesFromVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sports_keypoints_proto.ComputerVisionService/GetPoseImagesFromVideo',
            computervision__pb2.GetPoseImageRequest.SerializeToString,
            computervision__pb2.GetPoseImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoseDataFromVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sports_keypoints_proto.ComputerVisionService/GetPoseDataFromVideo',
            computervision__pb2.GetPoseDataRequest.SerializeToString,
            computervision__pb2.GetPoseDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoseHandImagesFromVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sports_keypoints_proto.ComputerVisionService/GetPoseHandImagesFromVideo',
            computervision__pb2.GetPoseHandImageRequest.SerializeToString,
            computervision__pb2.GetPoseHandImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoseHandDataFromVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sports_keypoints_proto.ComputerVisionService/GetPoseHandDataFromVideo',
            computervision__pb2.GetPoseHandDataRequest.SerializeToString,
            computervision__pb2.GetPoseHandDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPoseAllFromVideo(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/sports_keypoints_proto.ComputerVisionService/GetPoseAllFromVideo',
            computervision__pb2.GetPoseAllRequest.SerializeToString,
            computervision__pb2.GetPoseAllResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
