syntax = "proto3";
package sports_keypoints_proto;

message Double {
    double data = 1;
    string warning = 2; // optional
}

message Datapoint {
    double x = 1;
    double y = 2;
    double confidence = 3;
}

message Line {
    Datapoint first_point_on_line = 1;
    Datapoint second_point_on_line = 2;
}

message Body25PoseDatapoints {
    Datapoint nose = 1;
    Datapoint neck = 2;
    Datapoint r_shoulder = 3;
    Datapoint r_elbow = 4;
    Datapoint r_wrist = 5;
    Datapoint l_shoulder = 6;
    Datapoint l_elbow = 7;
    Datapoint l_wrist = 8;
    Datapoint midhip = 9;
    Datapoint r_hip = 10;
    Datapoint r_knee = 11;
    Datapoint r_ankle = 12;
    Datapoint l_hip = 13;
    Datapoint l_knee = 14;
    Datapoint l_ankle = 15;
    Datapoint r_eye = 16;
    Datapoint l_eye = 17;
    Datapoint r_ear = 18;
    Datapoint l_ear = 19;
    Datapoint l_big_toe = 20;
    Datapoint l_small_toe = 21;
    Datapoint l_heel = 22;
    Datapoint r_big_toe = 23;
    Datapoint r_small_toe = 24;
    Datapoint r_heel = 25;
}

message Body25HandDatapoints {
    Datapoint l_wrist = 1;
    Datapoint l_thumb1 = 2;
    Datapoint l_thumb2 = 3;
    Datapoint l_thumb3 = 4;
    Datapoint l_thumb = 5;
    Datapoint l_index1 = 6;
    Datapoint l_index2 = 7;
    Datapoint l_index3 = 8;
    Datapoint l_index = 9;
    Datapoint l_middle1 = 10;
    Datapoint l_middle2 = 11;
    Datapoint l_middle3 = 12;
    Datapoint l_middle = 13;
    Datapoint l_ring1 = 14;
    Datapoint l_ring2 = 15;
    Datapoint l_ring3 = 16;
    Datapoint l_ring = 17;
    Datapoint l_pinky1 = 18;
    Datapoint l_pinky2 = 19;
    Datapoint l_pinky3 = 20;
    Datapoint l_pinky = 21;
    Datapoint r_wrist = 22;
    Datapoint r_thumb1 = 23;
    Datapoint r_thumb2 = 24;
    Datapoint r_thumb3 = 25;
    Datapoint r_thumb = 26;
    Datapoint r_index1 = 27;
    Datapoint r_index2 = 28;
    Datapoint r_index3 = 29;
    Datapoint r_index = 30;
    Datapoint r_middle1 = 31;
    Datapoint r_middle2 = 32;
    Datapoint r_middle3 = 33;
    Datapoint r_middle = 34;
    Datapoint r_ring1 = 35;
    Datapoint r_ring2 = 36;
    Datapoint r_ring3 = 37;
    Datapoint r_ring = 38;
    Datapoint r_pinky1 = 39;
    Datapoint r_pinky2 = 40;
    Datapoint r_pinky3 = 41;
    Datapoint r_pinky = 42;
}
