// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.13.0
// source: computervision.proto

package computervision

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DTLImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *DTLImage) Reset() {
	*x = DTLImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computervision_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DTLImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DTLImage) ProtoMessage() {}

func (x *DTLImage) ProtoReflect() protoreflect.Message {
	mi := &file_computervision_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DTLImage.ProtoReflect.Descriptor instead.
func (*DTLImage) Descriptor() ([]byte, []int) {
	return file_computervision_proto_rawDescGZIP(), []int{0}
}

func (x *DTLImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DTLImage) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type FaceOnImage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image []byte `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *FaceOnImage) Reset() {
	*x = FaceOnImage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_computervision_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaceOnImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaceOnImage) ProtoMessage() {}

func (x *FaceOnImage) ProtoReflect() protoreflect.Message {
	mi := &file_computervision_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaceOnImage.ProtoReflect.Descriptor instead.
func (*FaceOnImage) Descriptor() ([]byte, []int) {
	return file_computervision_proto_rawDescGZIP(), []int{1}
}

func (x *FaceOnImage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FaceOnImage) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

var File_computervision_proto protoreflect.FileDescriptor

var file_computervision_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x72, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x08, 0x44, 0x54, 0x4c, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x37, 0x0a, 0x0b,
	0x46, 0x61, 0x63, 0x65, 0x4f, 0x6e, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x32, 0x7f, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65,
	0x72, 0x56, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4f, 0x70,
	0x65, 0x6e, 0x50, 0x6f, 0x73, 0x65, 0x44, 0x54, 0x4c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x09,
	0x2e, 0x44, 0x54, 0x4c, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x1a, 0x09, 0x2e, 0x44, 0x54, 0x4c, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x12, 0x3a, 0x0a, 0x16, 0x47, 0x65,
	0x74, 0x4f, 0x70, 0x65, 0x6e, 0x50, 0x6f, 0x73, 0x65, 0x46, 0x61, 0x63, 0x65, 0x4f, 0x6e, 0x49,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x0c, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x4f, 0x6e, 0x49, 0x6d, 0x61,
	0x67, 0x65, 0x1a, 0x0c, 0x2e, 0x46, 0x61, 0x63, 0x65, 0x4f, 0x6e, 0x49, 0x6d, 0x61, 0x67, 0x65,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_computervision_proto_rawDescOnce sync.Once
	file_computervision_proto_rawDescData = file_computervision_proto_rawDesc
)

func file_computervision_proto_rawDescGZIP() []byte {
	file_computervision_proto_rawDescOnce.Do(func() {
		file_computervision_proto_rawDescData = protoimpl.X.CompressGZIP(file_computervision_proto_rawDescData)
	})
	return file_computervision_proto_rawDescData
}

var file_computervision_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_computervision_proto_goTypes = []interface{}{
	(*DTLImage)(nil),    // 0: DTLImage
	(*FaceOnImage)(nil), // 1: FaceOnImage
}
var file_computervision_proto_depIdxs = []int32{
	0, // 0: ComputerVision.GetOpenPoseDTLImage:input_type -> DTLImage
	1, // 1: ComputerVision.GetOpenPoseFaceOnImage:input_type -> FaceOnImage
	0, // 2: ComputerVision.GetOpenPoseDTLImage:output_type -> DTLImage
	1, // 3: ComputerVision.GetOpenPoseFaceOnImage:output_type -> FaceOnImage
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_computervision_proto_init() }
func file_computervision_proto_init() {
	if File_computervision_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_computervision_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DTLImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_computervision_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaceOnImage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_computervision_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_computervision_proto_goTypes,
		DependencyIndexes: file_computervision_proto_depIdxs,
		MessageInfos:      file_computervision_proto_msgTypes,
	}.Build()
	File_computervision_proto = out.File
	file_computervision_proto_rawDesc = nil
	file_computervision_proto_goTypes = nil
	file_computervision_proto_depIdxs = nil
}
