// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package computervision

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ComputerVisionClient is the client API for ComputerVision service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ComputerVisionClient interface {
	GetOpenPoseDTLImage(ctx context.Context, opts ...grpc.CallOption) (ComputerVision_GetOpenPoseDTLImageClient, error)
	GetOpenPoseFaceOnImage(ctx context.Context, opts ...grpc.CallOption) (ComputerVision_GetOpenPoseFaceOnImageClient, error)
}

type computerVisionClient struct {
	cc grpc.ClientConnInterface
}

func NewComputerVisionClient(cc grpc.ClientConnInterface) ComputerVisionClient {
	return &computerVisionClient{cc}
}

func (c *computerVisionClient) GetOpenPoseDTLImage(ctx context.Context, opts ...grpc.CallOption) (ComputerVision_GetOpenPoseDTLImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ComputerVision_ServiceDesc.Streams[0], "/ComputerVision/GetOpenPoseDTLImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &computerVisionGetOpenPoseDTLImageClient{stream}
	return x, nil
}

type ComputerVision_GetOpenPoseDTLImageClient interface {
	Send(*DTLImage) error
	Recv() (*DTLImage, error)
	grpc.ClientStream
}

type computerVisionGetOpenPoseDTLImageClient struct {
	grpc.ClientStream
}

func (x *computerVisionGetOpenPoseDTLImageClient) Send(m *DTLImage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computerVisionGetOpenPoseDTLImageClient) Recv() (*DTLImage, error) {
	m := new(DTLImage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *computerVisionClient) GetOpenPoseFaceOnImage(ctx context.Context, opts ...grpc.CallOption) (ComputerVision_GetOpenPoseFaceOnImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &ComputerVision_ServiceDesc.Streams[1], "/ComputerVision/GetOpenPoseFaceOnImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &computerVisionGetOpenPoseFaceOnImageClient{stream}
	return x, nil
}

type ComputerVision_GetOpenPoseFaceOnImageClient interface {
	Send(*FaceOnImage) error
	Recv() (*FaceOnImage, error)
	grpc.ClientStream
}

type computerVisionGetOpenPoseFaceOnImageClient struct {
	grpc.ClientStream
}

func (x *computerVisionGetOpenPoseFaceOnImageClient) Send(m *FaceOnImage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computerVisionGetOpenPoseFaceOnImageClient) Recv() (*FaceOnImage, error) {
	m := new(FaceOnImage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ComputerVisionServer is the server API for ComputerVision service.
// All implementations must embed UnimplementedComputerVisionServer
// for forward compatibility
type ComputerVisionServer interface {
	GetOpenPoseDTLImage(ComputerVision_GetOpenPoseDTLImageServer) error
	GetOpenPoseFaceOnImage(ComputerVision_GetOpenPoseFaceOnImageServer) error
	mustEmbedUnimplementedComputerVisionServer()
}

// UnimplementedComputerVisionServer must be embedded to have forward compatible implementations.
type UnimplementedComputerVisionServer struct {
}

func (UnimplementedComputerVisionServer) GetOpenPoseDTLImage(ComputerVision_GetOpenPoseDTLImageServer) error {
	return status.Errorf(codes.Unimplemented, "method GetOpenPoseDTLImage not implemented")
}
func (UnimplementedComputerVisionServer) GetOpenPoseFaceOnImage(ComputerVision_GetOpenPoseFaceOnImageServer) error {
	return status.Errorf(codes.Unimplemented, "method GetOpenPoseFaceOnImage not implemented")
}
func (UnimplementedComputerVisionServer) mustEmbedUnimplementedComputerVisionServer() {}

// UnsafeComputerVisionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputerVisionServer will
// result in compilation errors.
type UnsafeComputerVisionServer interface {
	mustEmbedUnimplementedComputerVisionServer()
}

func RegisterComputerVisionServer(s grpc.ServiceRegistrar, srv ComputerVisionServer) {
	s.RegisterService(&ComputerVision_ServiceDesc, srv)
}

func _ComputerVision_GetOpenPoseDTLImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputerVisionServer).GetOpenPoseDTLImage(&computerVisionGetOpenPoseDTLImageServer{stream})
}

type ComputerVision_GetOpenPoseDTLImageServer interface {
	Send(*DTLImage) error
	Recv() (*DTLImage, error)
	grpc.ServerStream
}

type computerVisionGetOpenPoseDTLImageServer struct {
	grpc.ServerStream
}

func (x *computerVisionGetOpenPoseDTLImageServer) Send(m *DTLImage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computerVisionGetOpenPoseDTLImageServer) Recv() (*DTLImage, error) {
	m := new(DTLImage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ComputerVision_GetOpenPoseFaceOnImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputerVisionServer).GetOpenPoseFaceOnImage(&computerVisionGetOpenPoseFaceOnImageServer{stream})
}

type ComputerVision_GetOpenPoseFaceOnImageServer interface {
	Send(*FaceOnImage) error
	Recv() (*FaceOnImage, error)
	grpc.ServerStream
}

type computerVisionGetOpenPoseFaceOnImageServer struct {
	grpc.ServerStream
}

func (x *computerVisionGetOpenPoseFaceOnImageServer) Send(m *FaceOnImage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computerVisionGetOpenPoseFaceOnImageServer) Recv() (*FaceOnImage, error) {
	m := new(FaceOnImage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ComputerVision_ServiceDesc is the grpc.ServiceDesc for ComputerVision service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ComputerVision_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ComputerVision",
	HandlerType: (*ComputerVisionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOpenPoseDTLImage",
			Handler:       _ComputerVision_GetOpenPoseDTLImage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "GetOpenPoseFaceOnImage",
			Handler:       _ComputerVision_GetOpenPoseFaceOnImage_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "computervision.proto",
}
