# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import computervision_pb2 as computervision__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in computervision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ComputerVisionStub(object):
    """TODO Probably do a streaming rpc for large data
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetOpenPoseDTLImage = channel.stream_stream(
                '/ComputerVision/GetOpenPoseDTLImage',
                request_serializer=computervision__pb2.DTLImage.SerializeToString,
                response_deserializer=computervision__pb2.DTLImage.FromString,
                _registered_method=True)
        self.GetOpenPoseFaceOnImage = channel.stream_stream(
                '/ComputerVision/GetOpenPoseFaceOnImage',
                request_serializer=computervision__pb2.FaceOnImage.SerializeToString,
                response_deserializer=computervision__pb2.FaceOnImage.FromString,
                _registered_method=True)


class ComputerVisionServicer(object):
    """TODO Probably do a streaming rpc for large data
    """

    def GetOpenPoseDTLImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOpenPoseFaceOnImage(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ComputerVisionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetOpenPoseDTLImage': grpc.stream_stream_rpc_method_handler(
                    servicer.GetOpenPoseDTLImage,
                    request_deserializer=computervision__pb2.DTLImage.FromString,
                    response_serializer=computervision__pb2.DTLImage.SerializeToString,
            ),
            'GetOpenPoseFaceOnImage': grpc.stream_stream_rpc_method_handler(
                    servicer.GetOpenPoseFaceOnImage,
                    request_deserializer=computervision__pb2.FaceOnImage.FromString,
                    response_serializer=computervision__pb2.FaceOnImage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ComputerVision', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ComputerVision', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ComputerVision(object):
    """TODO Probably do a streaming rpc for large data
    """

    @staticmethod
    def GetOpenPoseDTLImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ComputerVision/GetOpenPoseDTLImage',
            computervision__pb2.DTLImage.SerializeToString,
            computervision__pb2.DTLImage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOpenPoseFaceOnImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/ComputerVision/GetOpenPoseFaceOnImage',
            computervision__pb2.FaceOnImage.SerializeToString,
            computervision__pb2.FaceOnImage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
