# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: computervision.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'computervision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63omputervision.proto\"\'\n\x08\x44TLImage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\"*\n\x0b\x46\x61\x63\x65OnImage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\x0c\x32\x7f\n\x0e\x43omputerVision\x12\x31\n\x13GetOpenPoseDTLImage\x12\t.DTLImage\x1a\t.DTLImage\"\x00(\x01\x30\x01\x12:\n\x16GetOpenPoseFaceOnImage\x12\x0c.FaceOnImage\x1a\x0c.FaceOnImage\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'computervision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DTLIMAGE']._serialized_start=24
  _globals['_DTLIMAGE']._serialized_end=63
  _globals['_FACEONIMAGE']._serialized_start=65
  _globals['_FACEONIMAGE']._serialized_end=107
  _globals['_COMPUTERVISION']._serialized_start=109
  _globals['_COMPUTERVISION']._serialized_end=236
# @@protoc_insertion_point(module_scope)
