# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import golfkeypoints_pb2 as golfkeypoints__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in golfkeypoints_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GolfKeypointsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadInputImage = channel.unary_unary(
                '/sports_keypoints_proto.GolfKeypointsService/UploadInputImage',
                request_serializer=golfkeypoints__pb2.UploadInputImageRequest.SerializeToString,
                response_deserializer=golfkeypoints__pb2.UploadInputImageResponse.FromString,
                _registered_method=True)
        self.ListInputImagesForUser = channel.unary_unary(
                '/sports_keypoints_proto.GolfKeypointsService/ListInputImagesForUser',
                request_serializer=golfkeypoints__pb2.ListInputImagesForUserRequest.SerializeToString,
                response_deserializer=golfkeypoints__pb2.ListInputImagesForUserResponse.FromString,
                _registered_method=True)
        self.ReadInputImage = channel.unary_unary(
                '/sports_keypoints_proto.GolfKeypointsService/ReadInputImage',
                request_serializer=golfkeypoints__pb2.ReadInputImageRequest.SerializeToString,
                response_deserializer=golfkeypoints__pb2.ReadInputImageResponse.FromString,
                _registered_method=True)
        self.DeleteInputImage = channel.unary_unary(
                '/sports_keypoints_proto.GolfKeypointsService/DeleteInputImage',
                request_serializer=golfkeypoints__pb2.DeleteInputImageRequest.SerializeToString,
                response_deserializer=golfkeypoints__pb2.DeleteInputImageResponse.FromString,
                _registered_method=True)
        self.CalibrateInputImage = channel.unary_unary(
                '/sports_keypoints_proto.GolfKeypointsService/CalibrateInputImage',
                request_serializer=golfkeypoints__pb2.CalibrateInputImageRequest.SerializeToString,
                response_deserializer=golfkeypoints__pb2.CalibrateInputImageResponse.FromString,
                _registered_method=True)
        self.CalculateGolfKeypoints = channel.unary_unary(
                '/sports_keypoints_proto.GolfKeypointsService/CalculateGolfKeypoints',
                request_serializer=golfkeypoints__pb2.CalculateGolfKeypointsRequest.SerializeToString,
                response_deserializer=golfkeypoints__pb2.CalculateGolfKeypointsResponse.FromString,
                _registered_method=True)
        self.ReadGolfKeypoints = channel.unary_unary(
                '/sports_keypoints_proto.GolfKeypointsService/ReadGolfKeypoints',
                request_serializer=golfkeypoints__pb2.ReadGolfKeypointsRequest.SerializeToString,
                response_deserializer=golfkeypoints__pb2.ReadGolfKeypointsResponse.FromString,
                _registered_method=True)
        self.UpdateBodyKeypoints = channel.unary_unary(
                '/sports_keypoints_proto.GolfKeypointsService/UpdateBodyKeypoints',
                request_serializer=golfkeypoints__pb2.UpdateBodyKeypointsRequest.SerializeToString,
                response_deserializer=golfkeypoints__pb2.UpdateBodyKeypointsResponse.FromString,
                _registered_method=True)
        self.DeleteGolfKeypoints = channel.unary_unary(
                '/sports_keypoints_proto.GolfKeypointsService/DeleteGolfKeypoints',
                request_serializer=golfkeypoints__pb2.DeleteGolfKeypointsRequest.SerializeToString,
                response_deserializer=golfkeypoints__pb2.DeleteGolfKeypointsResponse.FromString,
                _registered_method=True)


class GolfKeypointsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadInputImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListInputImagesForUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadInputImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteInputImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalibrateInputImage(self, request, context):
        """optional if want specific keypoints
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateGolfKeypoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadGolfKeypoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateBodyKeypoints(self, request, context):
        """if estimated body keypoints are off or have low confidence, client can manually input where body parts are
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteGolfKeypoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GolfKeypointsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadInputImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadInputImage,
                    request_deserializer=golfkeypoints__pb2.UploadInputImageRequest.FromString,
                    response_serializer=golfkeypoints__pb2.UploadInputImageResponse.SerializeToString,
            ),
            'ListInputImagesForUser': grpc.unary_unary_rpc_method_handler(
                    servicer.ListInputImagesForUser,
                    request_deserializer=golfkeypoints__pb2.ListInputImagesForUserRequest.FromString,
                    response_serializer=golfkeypoints__pb2.ListInputImagesForUserResponse.SerializeToString,
            ),
            'ReadInputImage': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadInputImage,
                    request_deserializer=golfkeypoints__pb2.ReadInputImageRequest.FromString,
                    response_serializer=golfkeypoints__pb2.ReadInputImageResponse.SerializeToString,
            ),
            'DeleteInputImage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteInputImage,
                    request_deserializer=golfkeypoints__pb2.DeleteInputImageRequest.FromString,
                    response_serializer=golfkeypoints__pb2.DeleteInputImageResponse.SerializeToString,
            ),
            'CalibrateInputImage': grpc.unary_unary_rpc_method_handler(
                    servicer.CalibrateInputImage,
                    request_deserializer=golfkeypoints__pb2.CalibrateInputImageRequest.FromString,
                    response_serializer=golfkeypoints__pb2.CalibrateInputImageResponse.SerializeToString,
            ),
            'CalculateGolfKeypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateGolfKeypoints,
                    request_deserializer=golfkeypoints__pb2.CalculateGolfKeypointsRequest.FromString,
                    response_serializer=golfkeypoints__pb2.CalculateGolfKeypointsResponse.SerializeToString,
            ),
            'ReadGolfKeypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadGolfKeypoints,
                    request_deserializer=golfkeypoints__pb2.ReadGolfKeypointsRequest.FromString,
                    response_serializer=golfkeypoints__pb2.ReadGolfKeypointsResponse.SerializeToString,
            ),
            'UpdateBodyKeypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateBodyKeypoints,
                    request_deserializer=golfkeypoints__pb2.UpdateBodyKeypointsRequest.FromString,
                    response_serializer=golfkeypoints__pb2.UpdateBodyKeypointsResponse.SerializeToString,
            ),
            'DeleteGolfKeypoints': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteGolfKeypoints,
                    request_deserializer=golfkeypoints__pb2.DeleteGolfKeypointsRequest.FromString,
                    response_serializer=golfkeypoints__pb2.DeleteGolfKeypointsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sports_keypoints_proto.GolfKeypointsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sports_keypoints_proto.GolfKeypointsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GolfKeypointsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadInputImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.GolfKeypointsService/UploadInputImage',
            golfkeypoints__pb2.UploadInputImageRequest.SerializeToString,
            golfkeypoints__pb2.UploadInputImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListInputImagesForUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.GolfKeypointsService/ListInputImagesForUser',
            golfkeypoints__pb2.ListInputImagesForUserRequest.SerializeToString,
            golfkeypoints__pb2.ListInputImagesForUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadInputImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.GolfKeypointsService/ReadInputImage',
            golfkeypoints__pb2.ReadInputImageRequest.SerializeToString,
            golfkeypoints__pb2.ReadInputImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteInputImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.GolfKeypointsService/DeleteInputImage',
            golfkeypoints__pb2.DeleteInputImageRequest.SerializeToString,
            golfkeypoints__pb2.DeleteInputImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalibrateInputImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.GolfKeypointsService/CalibrateInputImage',
            golfkeypoints__pb2.CalibrateInputImageRequest.SerializeToString,
            golfkeypoints__pb2.CalibrateInputImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateGolfKeypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.GolfKeypointsService/CalculateGolfKeypoints',
            golfkeypoints__pb2.CalculateGolfKeypointsRequest.SerializeToString,
            golfkeypoints__pb2.CalculateGolfKeypointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadGolfKeypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.GolfKeypointsService/ReadGolfKeypoints',
            golfkeypoints__pb2.ReadGolfKeypointsRequest.SerializeToString,
            golfkeypoints__pb2.ReadGolfKeypointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateBodyKeypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.GolfKeypointsService/UpdateBodyKeypoints',
            golfkeypoints__pb2.UpdateBodyKeypointsRequest.SerializeToString,
            golfkeypoints__pb2.UpdateBodyKeypointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteGolfKeypoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sports_keypoints_proto.GolfKeypointsService/DeleteGolfKeypoints',
            golfkeypoints__pb2.DeleteGolfKeypointsRequest.SerializeToString,
            golfkeypoints__pb2.DeleteGolfKeypointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
