# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: user.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nuser.proto\x12\x16sports_keypoints_proto\"G\n\x11\x43reateUserRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"%\n\x12\x43reateUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\":\n\x13RegisterUserRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\">\n\x14RegisterUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rsession_token\x18\x02 \x01(\t\"(\n\x0fReadUserRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\"O\n\x10ReadUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12*\n\x04user\x18\x02 \x01(\x0b\x32\x1c.sports_keypoints_proto.User\"^\n\x11UpdateUserRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\"Y\n\x12UpdateUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x32\n\x0cupdated_user\x18\x03 \x01(\x0b\x32\x1c.sports_keypoints_proto.User\"*\n\x11\x44\x65leteUserRequest\x12\x15\n\rsession_token\x18\x01 \x01(\t\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"(\n\x04User\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t2\xf6\x03\n\x0bUserService\x12\x65\n\nCreateUser\x12).sports_keypoints_proto.CreateUserRequest\x1a*.sports_keypoints_proto.CreateUserResponse\"\x00\x12k\n\x0cRegisterUser\x12+.sports_keypoints_proto.RegisterUserRequest\x1a,.sports_keypoints_proto.RegisterUserResponse\"\x00\x12S\n\x08ReadUser\x12\'.sports_keypoints_proto.ReadUserRequest\x1a\x1c.sports_keypoints_proto.User\"\x00\x12W\n\nUpdateUser\x12).sports_keypoints_proto.UpdateUserRequest\x1a\x1c.sports_keypoints_proto.User\"\x00\x12\x65\n\nDeleteUser\x12).sports_keypoints_proto.DeleteUserRequest\x1a*.sports_keypoints_proto.DeleteUserResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEUSERREQUEST']._serialized_start=38
  _globals['_CREATEUSERREQUEST']._serialized_end=109
  _globals['_CREATEUSERRESPONSE']._serialized_start=111
  _globals['_CREATEUSERRESPONSE']._serialized_end=148
  _globals['_REGISTERUSERREQUEST']._serialized_start=150
  _globals['_REGISTERUSERREQUEST']._serialized_end=208
  _globals['_REGISTERUSERRESPONSE']._serialized_start=210
  _globals['_REGISTERUSERRESPONSE']._serialized_end=272
  _globals['_READUSERREQUEST']._serialized_start=274
  _globals['_READUSERREQUEST']._serialized_end=314
  _globals['_READUSERRESPONSE']._serialized_start=316
  _globals['_READUSERRESPONSE']._serialized_end=395
  _globals['_UPDATEUSERREQUEST']._serialized_start=397
  _globals['_UPDATEUSERREQUEST']._serialized_end=491
  _globals['_UPDATEUSERRESPONSE']._serialized_start=493
  _globals['_UPDATEUSERRESPONSE']._serialized_end=582
  _globals['_DELETEUSERREQUEST']._serialized_start=584
  _globals['_DELETEUSERREQUEST']._serialized_end=626
  _globals['_DELETEUSERRESPONSE']._serialized_start=628
  _globals['_DELETEUSERRESPONSE']._serialized_end=665
  _globals['_USER']._serialized_start=667
  _globals['_USER']._serialized_end=707
  _globals['_USERSERVICE']._serialized_start=710
  _globals['_USERSERVICE']._serialized_end=1212
# @@protoc_insertion_point(module_scope)
